import { useEffect, useState } from 'react';
import { api } from './services/api.js';

const today = new Date().toISOString().slice(0, 10);
const navItems = [['dashboard', 'Dashboard'], ['students', 'Students'], ['mark', 'Mark Attendance'], ['review', 'Review Attendance'], ['history', 'Student History'], ['low', 'Low Attendance']];

function Alert({ message, type = 'danger' }) { return message ? <div className={`alert alert-${type}`} role="alert">{message}</div> : null; }
function Select({ label, value, onChange, children, disabled = false }) { return <div><label className="form-label">{label}</label><select className="form-select" value={value} onChange={(event) => onChange(event.target.value)} disabled={disabled}><option value="">Select {label.toLowerCase()}</option>{children}</select></div>; }
function StatCard({ label, value, tone }) { return <div className="col-md-3"><div className={`stat-card ${tone}`}><span>{label}</span><strong>{value ?? '-'}</strong></div></div>; }

function Login({ onLogin }) {
  const [form, setForm] = useState({ email: 'faculty@example.com', password: 'password' });
  const [error, setError] = useState('');
  const submit = async (event) => { event.preventDefault(); try { setError(''); const result = await api.login(form); onLogin(result.user); } catch (err) { setError(err.message); } };
  return <main className="login-shell"><section className="login-panel"><div className="brand-mark">SA</div><p className="eyebrow">Faculty workspace</p><h1>Smart attendance,<br /><em>kept accountable.</em></h1><p className="text-secondary mb-4">Record, review, and correct classroom attendance from one focused workspace.</p><form onSubmit={submit}><Alert message={error} /><label className="form-label">Email</label><input className="form-control form-control-lg mb-3" type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} required /><label className="form-label">Password</label><input className="form-control form-control-lg mb-4" type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} required /><button className="btn btn-dark btn-lg w-100">Sign in</button></form></section><aside className="login-aside"><span className="display-number">75%</span><p>Keep an eye on the attendance threshold that matters.</p></aside></main>;
}

function Dashboard({ setPage }) {
  const [stats, setStats] = useState({});
  useEffect(() => { api.dashboard().then(setStats).catch(() => {}); }, []);
  return <><PageHeader eyebrow="Overview" title="Good morning, faculty." description="A clear view of what needs your attention today." action={<button className="btn btn-dark" onClick={() => setPage('mark')}>Mark attendance</button>} /><div className="row g-3 mb-4"><StatCard label="Total students" value={stats.students} tone="blue" /><StatCard label="Subjects" value={stats.subjects} tone="yellow" /><StatCard label="Today's records" value={stats.todayAttendance} tone="green" /><StatCard label="Below 75%" value={stats.lowAttendance} tone="red" /></div><div className="empty-board"><div><span className="eyebrow">Core workflow</span><h2>Every record tells a story.</h2><p>Start by recording today’s class, then use review and history to keep the data accurate.</p></div><div className="workflow-list"><button onClick={() => setPage('mark')}><b>01</b><span>Record attendance</span><span>→</span></button><button onClick={() => setPage('review')}><b>02</b><span>Review and correct</span><span>→</span></button><button onClick={() => setPage('low')}><b>03</b><span>Catch low attendance</span><span>→</span></button></div></div></>;
}

function PageHeader({ eyebrow, title, description, action }) { return <div className="page-header d-flex justify-content-between align-items-end mb-4"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>; }

function Students({ departments, sections }) {
  const [students, setStudents] = useState([]); const [search, setSearch] = useState(''); const [showForm, setShowForm] = useState(false); const [message, setMessage] = useState(''); const [form, setForm] = useState({ rollNumber: '', name: '', email: '', departmentId: '', sectionId: '' });
  const load = () => api.students({ search }).then(setStudents).catch((err) => setMessage(err.message)); useEffect(() => { load(); }, []);
  const update = (key, value) => setForm({ ...form, [key]: value, ...(key === 'departmentId' ? { sectionId: '' } : {}) });
  const submit = async (event) => { event.preventDefault(); try { await api.addStudent(form); setMessage('Student added successfully.'); setForm({ rollNumber: '', name: '', email: '', departmentId: '', sectionId: '' }); setShowForm(false); load(); } catch (err) { setMessage(err.message); } };
  return <><PageHeader eyebrow="People" title="Students" description="Browse the students in your teaching groups." action={<button className="btn btn-dark" onClick={() => setShowForm(!showForm)}>{showForm ? 'Close form' : '+ Add student'}</button>} /><Alert message={message} type={message.includes('successfully') ? 'success' : 'danger'} />{showForm && <form className="form-strip mb-4" onSubmit={submit}><div className="row g-3"><div className="col-md-4"><label className="form-label">Roll number</label><input className="form-control" value={form.rollNumber} onChange={(e) => update('rollNumber', e.target.value)} required /></div><div className="col-md-4"><label className="form-label">Name</label><input className="form-control" value={form.name} onChange={(e) => update('name', e.target.value)} required /></div><div className="col-md-4"><label className="form-label">Email</label><input className="form-control" type="email" value={form.email} onChange={(e) => update('email', e.target.value)} required /></div><div className="col-md-5"><Select label="Department" value={form.departmentId} onChange={(v) => update('departmentId', v)}>{departments.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</Select></div><div className="col-md-5"><Select label="Section" value={form.sectionId} onChange={(v) => update('sectionId', v)} disabled={!form.departmentId}>{sections.filter((item) => String(item.departmentId?._id || item.departmentId) === form.departmentId).map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</Select></div><div className="col-md-2 d-flex align-items-end"><button className="btn btn-dark w-100">Save</button></div></div></form>}<div className="table-panel"><div className="table-tools"><input className="form-control" placeholder="Search by name or roll number" value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && load()} /><button className="btn btn-outline-dark" onClick={load}>Search</button></div><DataTable columns={['Roll number', 'Name', 'Email', 'Department', 'Section']} rows={students.map((student) => [student.rollNumber, student.name, student.email, student.departmentId?.name, student.sectionId?.name])} empty="No students found." /></div></>;
}

function AttendanceForm({ faculty, departments, sections, subjects }) {
  const [filters, setFilters] = useState({ departmentId: '', sectionId: '', subjectId: '', date: today }); const [students, setStudents] = useState([]); const [statuses, setStatuses] = useState({}); const [message, setMessage] = useState('');
  const update = (key, value) => setFilters({ ...filters, [key]: value, ...(key === 'departmentId' ? { sectionId: '' } : {}) });
  const load = async () => { if (!filters.sectionId || !filters.subjectId || !filters.date) return setMessage('Select a section, subject, and date first.'); try { const result = await api.students({ sectionId: filters.sectionId }); setStudents(result); setStatuses(Object.fromEntries(result.map((student) => [student._id, 'PRESENT']))); setMessage(''); } catch (err) { setMessage(err.message); } };
  const save = async () => { try { await api.saveAttendance({ subjectId: filters.subjectId, facultyId: faculty._id, date: filters.date, records: students.map((student) => ({ studentId: student._id, status: statuses[student._id] })) }); setMessage('Attendance saved successfully.'); } catch (err) { setMessage(err.message); } };
  return <><PageHeader eyebrow="Daily record" title="Mark attendance" description="Choose a class and set the status for every student." /><div className="form-strip mb-4"><div className="row g-3 align-items-end"><div className="col-md-3"><Select label="Department" value={filters.departmentId} onChange={(v) => update('departmentId', v)}>{departments.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</Select></div><div className="col-md-3"><Select label="Section" value={filters.sectionId} onChange={(v) => update('sectionId', v)} disabled={!filters.departmentId}>{sections.filter((item) => String(item.departmentId?._id || item.departmentId) === filters.departmentId).map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</Select></div><div className="col-md-3"><Select label="Subject" value={filters.subjectId} onChange={(v) => update('subjectId', v)} disabled={!filters.departmentId}>{subjects.filter((item) => String(item.departmentId?._id || item.departmentId) === filters.departmentId).map((item) => <option key={item._id} value={item._id}>{item.code} · {item.name}</option>)}</Select></div><div className="col-md-2"><label className="form-label">Date</label><input className="form-control" type="date" value={filters.date} onChange={(e) => update('date', e.target.value)} /></div><div className="col-md-1"><button className="btn btn-outline-dark w-100" onClick={load}>Load</button></div></div></div><Alert message={message} type={message.includes('successfully') ? 'success' : 'danger'} />{students.length > 0 && <div className="table-panel"><div className="table-tools"><span className="text-secondary">{students.length} students · {filters.date}</span><button className="btn btn-dark" onClick={save}>Save attendance</button></div><table className="table align-middle"><thead><tr><th>Roll number</th><th>Student</th><th>Status</th></tr></thead><tbody>{students.map((student) => <tr key={student._id}><td className="fw-semibold">{student.rollNumber}</td><td>{student.name}</td><td><div className="status-toggle"><button className={statuses[student._id] === 'PRESENT' ? 'active-present' : ''} onClick={() => setStatuses({ ...statuses, [student._id]: 'PRESENT' })}>Present</button><button className={statuses[student._id] === 'ABSENT' ? 'active-absent' : ''} onClick={() => setStatuses({ ...statuses, [student._id]: 'ABSENT' })}>Absent</button></div></td></tr>)}</tbody></table></div>}</>;
}

function Review({ departments, sections, subjects }) { const [filters, setFilters] = useState({ departmentId: '', sectionId: '', subjectId: '', date: '' }); const [records, setRecords] = useState([]); const [message, setMessage] = useState(''); const load = () => api.attendance(Object.fromEntries(Object.entries(filters).filter(([, value]) => value))).then(setRecords).catch((err) => setMessage(err.message)); useEffect(() => { load(); }, []); const update = async (record, status) => { try { await api.updateAttendance(record._id, status); setMessage('Attendance corrected.'); load(); } catch (err) { setMessage(err.message); } }; return <><PageHeader eyebrow="Accuracy" title="Review attendance" description="Inspect saved records and correct a status without creating duplicates." /><div className="form-strip mb-4"><div className="row g-3 align-items-end"><div className="col-md-3"><Select label="Department" value={filters.departmentId} onChange={(v) => setFilters({ ...filters, departmentId: v, sectionId: '' })}>{departments.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</Select></div><div className="col-md-3"><Select label="Section" value={filters.sectionId} onChange={(v) => setFilters({ ...filters, sectionId: v })}>{sections.filter((item) => !filters.departmentId || String(item.departmentId?._id || item.departmentId) === filters.departmentId).map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</Select></div><div className="col-md-3"><Select label="Subject" value={filters.subjectId} onChange={(v) => setFilters({ ...filters, subjectId: v })}>{subjects.map((item) => <option key={item._id} value={item._id}>{item.code} · {item.name}</option>)}</Select></div><div className="col-md-2"><label className="form-label">Date</label><input className="form-control" type="date" value={filters.date} onChange={(e) => setFilters({ ...filters, date: e.target.value })} /></div><div className="col-md-1"><button className="btn btn-dark w-100" onClick={load}>Filter</button></div></div></div><Alert message={message} type="success" /><div className="table-panel"><DataTable columns={['Date', 'Student', 'Subject', 'Status', 'Correction']} rows={records.map((record) => [new Date(record.date).toLocaleDateString(), `${record.studentId?.rollNumber} · ${record.studentId?.name}`, record.subjectId?.name, <span className={`badge-status ${record.status.toLowerCase()}`}>{record.status}</span>, <select className="form-select form-select-sm" value={record.status} onChange={(e) => update(record, e.target.value)}><option>PRESENT</option><option>ABSENT</option></select>])} empty="No attendance records match these filters." /></div></>; }

function History({ students }) { const [studentId, setStudentId] = useState(''); const [data, setData] = useState(null); const [message, setMessage] = useState(''); const load = async (id) => { setStudentId(id); if (!id) return setData(null); try { setData(await api.studentHistory(id)); setMessage(''); } catch (err) { setMessage(err.message); } }; return <><PageHeader eyebrow="Student view" title="Attendance history" description="See subject-level totals and the underlying record trail." /><div className="form-strip mb-4"><Select label="Student" value={studentId} onChange={load}>{students.map((student) => <option key={student._id} value={student._id}>{student.rollNumber} · {student.name}</option>)}</Select></div><Alert message={message} />{data ? <><div className="row g-3 mb-4">{data.summaries.map((summary) => <div className="col-md-4" key={summary.subject._id}><div className="summary-card"><span>{summary.subject.code}</span><h3>{summary.percentage === null ? 'No data' : `${summary.percentage}%`}</h3><p>{summary.subject.name} · {summary.present} present of {summary.total}</p></div></div>)}</div><div className="table-panel"><DataTable columns={['Date', 'Subject', 'Status']} rows={data.records.map((record) => [new Date(record.date).toLocaleDateString(), record.subjectId?.name, <span className={`badge-status ${record.status.toLowerCase()}`}>{record.status}</span>])} empty="No attendance data available." /></div></> : <div className="empty-state">Select a student to view their attendance history.</div>}</>; }

function LowAttendance({ departments, sections, subjects }) { const [filters, setFilters] = useState({ departmentId: '', sectionId: '', subjectId: '' }); const [results, setResults] = useState([]); const load = () => api.lowAttendance(Object.fromEntries(Object.entries(filters).filter(([, value]) => value))).then(setResults); useEffect(() => { load(); }, []); return <><PageHeader eyebrow="Threshold watch" title="Low attendance" description="Students below 75%, calculated from attendance records." /><div className="form-strip mb-4"><div className="row g-3 align-items-end"><div className="col-md-4"><Select label="Department" value={filters.departmentId} onChange={(v) => setFilters({ ...filters, departmentId: v, sectionId: '' })}>{departments.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</Select></div><div className="col-md-4"><Select label="Section" value={filters.sectionId} onChange={(v) => setFilters({ ...filters, sectionId: v })}>{sections.filter((item) => !filters.departmentId || String(item.departmentId?._id || item.departmentId) === filters.departmentId).map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</Select></div><div className="col-md-3"><Select label="Subject (optional)" value={filters.subjectId} onChange={(v) => setFilters({ ...filters, subjectId: v })}>{subjects.map((item) => <option key={item._id} value={item._id}>{item.code} · {item.name}</option>)}</Select></div><div className="col-md-1"><button className="btn btn-dark w-100" onClick={load}>Filter</button></div></div></div><div className="table-panel"><DataTable columns={['Student', 'Roll number', 'Department', 'Section', 'Attendance']} rows={results.map((entry) => [entry.student.name, entry.student.rollNumber, entry.student.departmentId?.name, entry.student.sectionId?.name, <strong className="text-danger">{entry.percentage}%</strong>])} empty="No students are below 75% in this scope." /></div></>; }

function DataTable({ columns, rows, empty }) { return rows.length ? <table className="table align-middle mb-0"><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table> : <div className="empty-state">{empty}</div>; }

export default function App() { const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('attendanceUser') || 'null')); const [page, setPage] = useState('dashboard'); const [departments, setDepartments] = useState([]); const [sections, setSections] = useState([]); const [subjects, setSubjects] = useState([]); const [students, setStudents] = useState([]); useEffect(() => { if (user) Promise.all([api.departments(), api.sections(), api.subjects(), api.students()]).then(([departmentsResult, sectionsResult, subjectsResult, studentsResult]) => { setDepartments(departmentsResult); setSections(sectionsResult); setSubjects(subjectsResult); setStudents(studentsResult); }).catch(() => {}); }, [user]); if (!user) return <Login onLogin={(nextUser) => { localStorage.setItem('attendanceUser', JSON.stringify(nextUser)); setUser(nextUser); }} />; const logout = () => { localStorage.removeItem('attendanceUser'); setUser(null); }; const pages = { dashboard: <Dashboard setPage={setPage} />, students: <Students departments={departments} sections={sections} />, mark: <AttendanceForm faculty={user} departments={departments} sections={sections} subjects={subjects} />, review: <Review departments={departments} sections={sections} subjects={subjects} />, history: <History students={students} />, low: <LowAttendance departments={departments} sections={sections} subjects={subjects} /> }; return <div className="app-shell"><aside className="sidebar"><div className="sidebar-brand"><div className="brand-mark">SA</div><div><strong>Smart Attendance</strong><small>Faculty workspace</small></div></div><nav>{navItems.map(([id, label]) => <button key={id} className={page === id ? 'active' : ''} onClick={() => setPage(id)}><span className={`nav-icon icon-${id}`}></span>{label}</button>)}</nav><div className="sidebar-user"><span className="avatar">{user.name?.slice(0, 1)}</span><div><strong>{user.name}</strong><small>{user.email}</small></div><button onClick={logout} title="Log out">↗</button></div></aside><main className="main-content">{pages[page]}</main></div>; }
